### ISSUE TITLE
Color and Style potential issue

### ISSUE THREAD

**Issue by mytech-today-now** [presenta-software/presenta-lib#10]
The way that you have implemented Color and Style might need reworking.

Immediately, I tried to do the following only to find it didn't work.  This type of behavior would be one that I would anticipate the software being able to do.  I expected to be able to change the formatting and colors from block to block.  The way that you have implemented, it only allows for one style and color per document.

---
colors: five
fonts: four
---
# Built-in Styles
### Fonts and Colors 
---
# Frontmatter
To change style properties you need to set the frontmatter (the top part of this document) and setting the <mark>colors</mark>, <mark>fonts</mark> and <mark>transition</mark> with proper values.
---
colors: two
fonts: one
---
# Fonts
There are **seven** font-sets built-in (from <mark>one</mark> to <mark>seven</mark>).
Each font-set has **two** variants, one for **Heading**, the other for **Text**.
---
colors: five
fonts: four
---
# Colors
There are **twelve** color-sets built-in (from <mark>one</mark> to <mark>twelve</mark>).
Each color-set contains **four** colors (background, text, accent, alternative).
---

BTW, I think the software is great!  I was working on something identical to it, but, in every way, Presenta is so much better than what I built.

**Comment by abusedmedia** [comment]
Hi @mytech-today-now 

Setting different styles is potentially feasible using the JSON definition (but I didn't verified yet, there might be issues, though).

Using the markdown version, there's a conflict issue in the parser, how to differentiate the frontmatter from the slide separator?

Here an example

```
---
colors: one
---

This is a slide

---
colors: two (but now it is a slide too)
---

This is a slide

```

BTW, do you have something published?

**Comment by mytech-today-now** [comment]
I would suggest using your notation already used for video
```video
---
```colors: two
---
I would suggest that you use ``` for all of your tagging if possible
or use some other tag to denote your commands.

Regarding my work:  All of my code is always garbage spaghetti code.  I'm not a coder.  I've product managed, designed, UX/UI, software-tested, used, and maintained, but never coded.  My personality doesn't allow me to sanely debug code :(   The work I was doing on my project was with other coders, and I can tell you that everything you've done with this is just such a better implementation of what I was envisioning than what I was creating myself.

**Comment by mytech-today-now** [comment]
Now that I've had more of a chance to play with presenta, I don't think this is such an issue anymore.
I have created a multipage present, and over the past day or two I have styled it, and between the custom fonts, alt settings, custom foreground, background and accent color, I think there is plenty of ways to style something in a visually appealing manner.  I think this can be closed.
