### ISSUE TITLE
Feature Suggestion - Ending destination URL

### ISSUE THREAD

**Issue by mytech-today-now** [presenta-software/presenta-lib#11]
So, in the software that I was designing, I had an optional 'Destination URL' at the end of the entire presentation.  You would be able to set a URL landing page at the end of the presentation.
Also, it t would be nice if the presentas could feed one after another.  So that I could set my presenta to end with the beginning of a new presenta.  Or, I can have it end at some other web page.

Something like:
```DestinationURL: https://www.google.com
or
```DestinationURL: https://www.domain.tld/new-presenta

I would ignore all, except for the last one on the markdown page in case some user decides to put multiple triggers per document.

**Comment by abusedmedia** [comment]
You could use the embed directive to include a landing page at the end of a presentation, such as:
https://play.presenta.cc/view/GvLnZG5uhvo54

**Comment by mytech-today-now** [comment]
I tried the same thing.  A lot of sites won't allow for embedding.  I'm not suggesting that everyone is going to embed FB, but it was an easy example.
![problem with embedding](https://user-images.githubusercontent.com/52089154/107729785-6ee13500-6cb7-11eb-9dd2-74ea39d5966b.png)

**Comment by abusedmedia** [comment]
A redirect feature at the end of the presentation (only in present mode) can be added as a plugin in PRESENTA, I guess.
Let's see if I can manage to it quickly...

**Comment by mytech-today-now** [comment]
It provides for the nice functionality of being able to put together a presenta presentation that dumps the user into a landing page.  So, the presenta can be the pitch and the final URL is the sale, for whatever the endeavor.  The destination URL can be whatever page the creator sets up on whatever site, say a sign-up page or a product 'buy' page.

**Comment by mytech-today-now** [comment]
The second neat trick that can make them viral is to ensure that you can link into another presenta, if that's easy to do.

**Comment by abusedmedia** [comment]
Here a quick test, when you present and reach the last slide, after a further `next` action you'll be redirect to any URL.
https://play.presenta.cc/view/vpZUKSKJaU6AG

**Comment by mytech-today-now** [comment]
That is the idea.  
Bug: 
Mouse clicking on the navigation arrows, on the horizontal edges of the screen:
If I use the "arrows" to navigate, the last block doesn't have a last "arrow" (on the right of the screen) to click on to go to the destination URL

Works perfectly with keyboard arrow keys:
If I use the keyboard arrows, everything works perfectly.  Each block is advanced with each "right arrow key" press, and on the final block, it exits to the destination URL, perfectly.

Otherwise, this is great, and it's great that you were able to do this so quickly.

**Comment by mytech-today-now** [comment]
This feature makes the whole piece of software much more attractive to sales forces, and marketing efforts.  
For example, a salesperson can quickly assemble a sales presentation with your software, that will dump the client into a buy now page at the end of the presentation.

This was one of my potential use cases for the software.

**Comment by abusedmedia** [comment]
Honestly, I've never thought such tool to be usefu and attractivel for sales people. Good to know. Curious to see some example if possible.

**Comment by mytech-today-now** [comment]
I tried to create a presenta with an Amazon Book link as the destination URL.
It site seems to get into an infinite loop with the Destination URL
It plays: a title, video, name of book with link, then destination URL
https://play.presenta.cc/view/hhKGIH6EBtkvE

**Comment by abusedmedia** [comment]
Hi @mytech-today-now 

you need to indent the `redirect` field within `controllers` field:

```
colors: one
plugins:
   - url: https://unpk...
controllers:
   redirect: https://....
```

Here the correct version:
https://play.presenta.cc/peek/iQ1yhFQIhR3qq#s2

**Comment by mytech-today-now** [comment]
Thank you, that solved every problem.

**Comment by abusedmedia** [comment]
I've refactored a bit the Home page to accomodate also examples and ideas from the community, thus, this specific sample is featured in Home page :)
