### ISSUE TITLE
Autoplay on videos and markdown list

### ISSUE THREAD

**Issue by mytech-today-now** [presenta-software/presenta-lib#12]
One of the use cases that I came up with for the software was as a media player.

Use case: someone is throwing a party (pre-covid days), or wake, or whatever.
They can create a markdownlist of youtube/vimeo/whatever/mp4 of videos, one video per block.
The playlist of videos would just auto play each one after another until the list was done.
I also had a loop list feature flag.

**Comment by mytech-today-now** [comment]
I guess in the design, I also had a plan for a randomize playback of the list,  but that was never implemented, just because.

**Comment by abusedmedia** [comment]
This is close to what you said, the trick is to use javascript instead markdown, that allows much more expressivity:

https://play.presenta.cc/view/q7OqCOkhHXNSZ

The only missing bit is that the duration of each video needs to be provided alongside the video source.
I guess there's room to modify the youtube plugin in order to let it automatically set it.

**Comment by mytech-today-now** [comment]
Ok, that is cool!  I didn't realize that you designed it this way.  This software that you developed is getting more impressive each time I look at it.

This will work for those dedicated to making it happen.  A more user-friendly way to create a playlist, if that's something that you want to pursue, is probably in order.  By requiring JS knowledge it eliminates most people, except programmers who already have millions of ways to create playlists.  A simpler creation method for creating these lists for that average user is what is needed to market that feature to that crowd, again if you so desire.

As it stands, the JS method of creating a media player is sufficient for the time being.

Again, just blown away.

**Comment by abusedmedia** [comment]
Also this example is featured in Home under "Ideas from Community" section.

**Comment by mytech-today-now** [comment]
Hi,

So, I was trying a simple enhancement to separate out the playlist into a separate file.
https://play.presenta.cc/view/j2gAcJxn30wZ0
This produces no playback for me.  The screen is blank (white) and nothing shows.  So, it is inconsistent with the results from the presenta below.


When I created this the playback of files in a separate file seem to work as expected (playing the videos, in order, from youtube, looped):  https://play.presenta.cc/view/y1ODik6sOIEzJ
