### ISSUE TITLE
Enhancement plugin - use of The Open Graph protocol for posting to social media

### ISSUE THREAD

**Issue by mytech-today-now** [presenta-software/presenta-lib#14]
https://ogp.me/
This is a future feature that will help.  If users are able to post their Presentas to FB & Twitter it will virally enhance the spread of the software's use.  I'm not sure what priority this is for you.

**Comment by abusedmedia** [comment]
I understand the benefit but this feature requires some server-side work for the preview generation. 
Maybe in the future, though.
