### ISSUE TITLE
Difficulty reseting the site and losing data

### ISSUE THREAD

**Issue by mytech-today-now** [presenta-software/presenta-lib#15]
As I play around in https://play.presenta.cc/

This is the manner in which I work.
I have notepadd++ with my markdown file.

I create in https://play.presenta.cc/ then either download markdown file or copy and paste back to notepad++ to save the changes.

If I try to view the presenta, when I click on the back button, all of my work is lost and I am back at the default example.

As it currently works, when I create a presenta and try to view it, all of the data is gone when I click on the browser back button (firefox).

The only point where my work shows up is when I go in a new tab to https://play.presenta.cc and click on the "use last presenta" link at the top.

Sometimes, the site will get so messed up that I need to clear the cache and cookies to reset the site.  After that all of my work is lost, but I can easily start again because I have my data in notepad++ or the downloaded markdown file.

It might be advisable to have a HARD RESET button that purges your cookies and stuff on the user's computer to give them a way to reset the site.  I know that won't work permanently, but it helps.

**Comment by abusedmedia** [comment]
Hi @mytech-today-now 

You should just edit within the tool, it saves locally, so no need to ping-pong with notepad++, unless you're resetting your browser local cache, in that case you need to download the document before clear the cache.

The Playground version saves locally just the last presentation you edit.
You can **view** any presentations without overwriting the one saved locally.
Once you **fork** a presentation, it becomes the last one overwriting the previous one.
If you resed your local cache, you erase the saved presentation.

A SaaS version with an online account and multiple documents is in the making, though.
