### ISSUE TITLE
Enhancement - Use ![title](URL) to flag a link to open in a new tab - "!"

### ISSUE THREAD

**Issue by mytech-today-now** [presenta-software/presenta-lib#16]
The way that you have it's currently designed:

If I want to make my link open in a new tab, I need to do this:

    <a href="https://domain.tdl/page.html" target="blank">Long complicated Title</a>

It would be easier if I could do this:

    ![Long complicated Title](https://domain.tdl/page.html)

**Comment by abusedmedia** [comment]
Hi @mytech-today-now 

Unfortunately `markdown` spec doesn't support the `target` attribute in links.
The solution you're using is the actual workaround in markdown space.
