### ISSUE TITLE
Maybe a 'toast' on videos to indicate to press space bar or click to play

### ISSUE THREAD

**Issue by mytech-today-now** [presenta-software/presenta-lib#19]
In my experience, users are clueless and will not initiate action, unless prompted.  I think it might be too subtle that the videos play when the user presses the space bar or click on the video.

It might be helpful to pop up a toast over each video when a new block appears, that indicates how to play a video.

Even better would be to 'toast the first video' and no others after that.

**Comment by abusedmedia** [comment]
There's a plugin for that I didn't published yet.
It's something that allows you to show a toast tip on a specific slide, with a custom text, delay and duration.

I use it in the Presenta splash page of the lib: https://lib.presenta.cc/
You can see the effect in the second to last slide.

I'll try to find the time to publish and document it.
Thanks.

**Comment by abusedmedia** [comment]
Hello there,
I've added an example that uses and explains the 'toast' plugin.
https://play.presenta.cc/view/yzSvcdiqxrv01

**Comment by abusedmedia** [comment]
I've updated the example that shows the toast plugin with an additional setting possibility, that is, you can set a delay time before to show the tip as well as the lasting time of the same:
https://play.presenta.cc/peek/mv8le8QkEt1kd
