### ISSUE TITLE
Viewing shared presenta is not exactly clear

### ISSUE THREAD

**Issue by mytech-today-now** [presenta-software/presenta-lib#20]
It's not exactly clear how to view a Presenta in full-screen mode when a user receives a shared link.
When the shared link appears, the user is given a small version of the presenta, and an "open in editor" link, and a "copy" link.

There should be a view link, as it is less than desirable to view the presenta in the small window.

Also, the way that you have it set up now, the user must go into the editor in order to view the presenta.  This is not an obvious step in the entire process.  Someone who gets one of these in an email for the first time will not understand how to navigate it if they simply want to view the slideshow.

**Comment by mytech-today-now** [comment]
I would suggest adding a "view" link on the share page, next to "Open in Editor" and the "Copy" link.

**Comment by abusedmedia** [comment]
A very good suggestion, thanks. 
Added to the pipeline.

**Comment by abusedmedia** [comment]
Added the 'present full window' button in shared view.
