### ISSUE TITLE
Iframe in block

### ISSUE THREAD

**Issue by mytech-today-now** [presenta-software/presenta-lib#22]
I tried to embed an amazon iframe into a block. but nothing appeared.

https://play.presenta.cc/view/GDVhZqdDssVgv

I'm not sure if this is expected behavior.  In some regards, I can use HTML, such as

`<a href="link" target="blank">thing</a>`

But others such as the iframe don't work.

**Comment by mytech-today-now** [comment]
This is a presenta with the correct embed structure and only the src

https://play.presenta.cc/view/xSa1eSrPOzsz9

**Comment by abusedmedia** [comment]
I guess Amazon does some checks blocking the embed for some reason.
