### ISSUE TITLE
Brave Browser don't respond as Chrome, firefox and edge - interface responses

### ISSUE THREAD

**Issue by mytech-today-now** [presenta-software/presenta-lib#23]
In the editor, the feature that slides the correct preview pane item into focus, when I click in the corresponding markdown block is broken.

**Comment by abusedmedia** [comment]
Hi

that's weird since Brave is based on Chromium.

I've tested it right now and I cannot see the issue.
Everything works as expected.

I can't reproduce the issue.

**Comment by mytech-today-now** [comment]
Brave - http://www.insidiousmeme.com/presenta/presenta_errors/2021-03-14-01-Pre-built-Computer-Recommendations%20_%20PRESENTA=Play!-Brave-2021-03-14%2013-12-10.mp4

Firefox - http://www.insidiousmeme.com/presenta/presenta_errors/2021-03-13-01-BTC-Report%20_%20PRESENTA-Play!%E2%80%94Mozilla-Firefox-2021-03-14%2013-11-22.mp4

**Comment by mytech-today-now** [comment]
It's not a big issue, in the Brave video you can see that selecting text in the markdown pane doesn't elicit a response from the preview pane.  It's an inconsistency in behavior between Firefox/Edge and Brave, since those are what I use

**Comment by abusedmedia** [comment]
I see. I cannot experience the same on my Mac, though.
What OS/version you're using?
