### ISSUE TITLE
Password protected beyond this slide block

### ISSUE THREAD

**Issue by mytech-today-now** [presenta-software/presenta-lib#27]
Hi, so I just developed a scenario where it would be advantageous to have the ability to write a block that requires a password to advance beyond.  There are several approaches to this problem if I were to write it, but all of them would suck.

If you have any quick and dirty thoughts on the matter, I'd love for this feature to be included.

If it could be a placeable block, rather than making the entire presentation locked, then I can create a presenta where there is an intro to the presentation, which is unlocked with the correct code.  I am assuming that the list of codes is kept on a server somewhere on the internet.

**Comment by abusedmedia** [comment]
Hi, such thing without a server-side auth is not very reliable.
Since you have to provide the password in some way, why not just providing a Presenta URL?
