### ISSUE TITLE
The play.presenta.cc website doesn't work in Safari

### ISSUE THREAD

**Issue by mytech-today-now** [presenta-software/presenta-lib#28]
When I have sent play.presenta.cc link to macOS users, Safari doesn't play the presentations.  They can play them in alternative browsers, tho

**Comment by abusedmedia** [comment]
Hi, as far as I know, I'm on Mac, on Safari 13.x works as expected. 
Do you know the Safari version in which it doesn't?

**Comment by mytech-today-now** [comment]
Matrix so far:
Doesn't Work:
1)
macOS: High Sierra 10.13.6
Safari: 11.1
2)
macOS: High Sierra 10.13.16
Safari: 13.1.2

Works Correctly:
1)
macOS: Mojave 10.14.6
Safari: 14.0.3

**Comment by abusedmedia** [comment]
Ok, Safari 11 might not work but 13.1.2 is the exactly version I have.
Can you post a specific presentation that doesn't work?

**Comment by mytech-today-now** [comment]
https://play.presenta.cc/view/I318lpMfkX8fJ

**Comment by abusedmedia** [comment]
Thanks. In my Safari works as expected. Can you tell me more precisely what happen?
- completely blank?
- broken rendering?
- other issue?

**Comment by mytech-today-now** [comment]
enless circling of the processing icon on a blank page

**Comment by abusedmedia** [comment]
Ok, so it looks like the plugin in that presentation doesn't load or get broken during initialization.
What can you see if you got straight to the home page? Do yu see all the examples? Are all in pending loading?
