### ISSUE TITLE
Pastebin chokes on presenta.cc domain.

### ISSUE THREAD

**Issue by mytech-today-now** [presenta-software/presenta-lib#31]
I created an example of a sample of [Examples of Presenta Markdown](https://play.presenta.cc/view/ch8oqpRy2G4Ix)

When I pasted the markdown code into pastebin, I received an error saying that your links, the presenta.cc example links were suspicious, and that I can only create a private paste in pastebin.  I've attached an actual example of what I pasted as well as the error I received.
[Example of Presenta Markdown.txt](https://github.com/presenta-software/presenta-lib/files/6517251/Example.of.Presenta.Markdown.txt)
![PAstebin choking on presenta cc domain](https://user-images.githubusercontent.com/52089154/119011133-5b9ad100-b95a-11eb-8d65-b4e5c0481498.png)

**Comment by abusedmedia** [comment]
Hi, I've used your file and removed all the URLs and it passes the block on Pastebin.
Just adding one URL, such as the Google Font one, Pastebin blocks the publishing.
This means that it blocks any sources that contains URLs, not the one with Presenta URL.
