### ISSUE TITLE
[Playground] Add visual feedback when the source is invalid

### ISSUE THREAD

**Issue by mytech-today-now** [presenta-software/presenta-lib#32]
Build: v0.3.49 0.1.19

I'm not sure if you are still working on the play.presenta.cc part of your project.

Lately, when I try to create presentas, the content of the page is not refreshing.  I have put together a short video that shows what is going on.  I have also attached the markdown that I was attempting to add.

https://user-images.githubusercontent.com/52089154/119066992-ae01df00-b9a6-11eb-9742-6df5a87c6f6a.mp4

[2021-05-20 - Error generating presenta - Markdown Content.txt](https://github.com/presenta-software/presenta-lib/files/6519420/2021-05-20.-.Error.generating.presenta.-.Markdown.Content.txt)

**Comment by abusedmedia** [comment]
Hi,
the rendering is blocked because there's a error in the source.
The following _video part:
```
https://cdn.shopify.com/s/files/1/2065/8833/files/5_Smart_CAPTURE.mp4
```

requires:
```
url: https://cdn.shopify.com/s/files/1/2065/8833/files/5_Smart_CAPTURE.mp4
```

I think that a feedback about the error might help the user.
Thanks for posting it.

**Comment by abusedmedia** [comment]
Just deployed the v0.3.50 that adds a visual feedback when the source is not compilable due some errors, thus, the user is notified about the render blocked.
