### ISSUE TITLE
Account suspended on https://app.presenta.cc/login

### ISSUE THREAD

**Issue by mytech-today-now** [presenta-software/presenta-lib#50]
I played with the software when it was first released.  Haven't really thought about it much when I realized it would work for my needs as it was currently working.  Came back today to see it it meets my needs, requested a password reset, reset my password to find out my account is suspended.🤔

user: kyle@mytech.today

What gives?

Can someone in the group there take a look and take care of it.

Thanks,
😉

**Comment by abusedmedia** [comment]
Solved
