### ISSUE TITLE
Nested lists with markdown not working

### ISSUE THREAD

**Issue by nachtfunke** [presenta-software/presenta-lib#6]
Hello! It seems that nested lists with markdown syntax have a bit of a counterintuitive styling. This it how it looks with one and two tabs:

![nested list 1 tab](https://i.imgur.com/GCQCwwK.png)

This is how it looks from the third tab on:

![nested list 3 tabs](https://i.imgur.com/ZT2KtUG.png)

**Comment by abusedmedia** [comment]
Hi @nachtfunke 

You're right, there's definitely a CSS issue in there.
 
Thanks to reporting it!

**Comment by abusedmedia** [comment]
Hi @nachtfunke I've put a patch to this issue, you can see an example here:
https://play.presenta.cc/view/McTt5556mc435

Let me know if it works now
Best
