### ISSUE TITLE
how to use presenta as vue component？

### ISSUE THREAD

**Issue by swuecho** [presenta-software/presenta-lib#8]
tring to use presenta in vue. watch  the editor and update presenta. 

in a watch function: 

```
let parsed = md2pjson.parse(val);
new Presenta("#presenta", parsed);
```

However, every change in val will create a new Presenta. 

also tried.

```
if (this.presenta) {
          this.prenseta.then(pres => pres.destroy())
      }
 this.prenseta = new Presenta("#presenta", parsed);
```

still no luck.

What is the correct way to use presenta in vue? Thanks.

**Comment by abusedmedia** [comment]
Hi @swuecho 

here a bare-bones example of a markdown editor to Presenta in Vue:
https://codepen.io/abusedmedia/pen/gOwJMEb

Let me know if it helps!

Fabio

**Comment by swuecho** [comment]
Hi @abusedmedia ,

works great. Thanks.
