### ISSUE TITLE
Common Anti-virus software tags .cc tld as virus site

### ISSUE THREAD

**Issue by mytech-today-now** [presenta-software/presenta-lib#9]
I know there's not much you can do about this.  I just want to make you aware of the default message when I try to connect with a computer running Malwarebytes anti-virus.
![malwarebytes - tld-scam-warning-presenta cc](https://user-images.githubusercontent.com/52089154/107365874-03bf1500-6aa3-11eb-8f5e-9aeda09e4f55.png)

**Comment by mytech-today-now** [comment]
Avira Malware software doesn't alert on your site

**Comment by abusedmedia** [comment]
Hi @mytech-today-now,

Thanks for reporting it.

As you already said, I can't do much on it, I guess.

To be fair, that's a very weird way to suspect bad activity of a website, but still.
